apiVersion: v1
   kind: Service
   metadata:
     name: {{ .Release.Name }}-nodejs-sample
     labels:
       app: nodejs-sample
   spec:
     selector:
       app: nodejs-sample
     ports:
       - protocol: TCP
         port: {{ .Values.service.port }}
         targetPort: {{ .Values.service.targetPort }}
     type: {{ .Values.service.type }}
