pipeline:
  identifier: Build_wowitsbala_nodejsapp_1751302511556
  name: Build nodejsapp
  orgIdentifier: default
  projectIdentifier: Project003
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1750965264531
        repoName: wowitsbala/nodejsapp
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          caching:
            enabled: true
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: test
                  name: test
                  spec:
                    command: npm run test
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI
